server:
  port: 9000
spring:
  application:
    name: boot-admin-server
  boot:
    admin:
      routes:
        endpoints: env, metrics, trace, dump, jolokia, info, configprops, activiti, logfile, refresh, flyway, liquibase, loggers,hystrix.stream,activiti
      turbine:
        clusters: default
        location: netflix-turbine-monitor
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    #添加eureka.instance.metadata-map.user.name和eureka.instance.metadata-map.user.name 否则在安全模式下无法注册
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
management:
  security:
    enabled: false
endpoints:
  enabled: true
  shutdown:
    enabled: false
info:
  app:
    encoding: UTF-8
    java:
      source: 1.8
      target: 1.8
    head: ${spring.application.name}
    body: Welcome, this is ${spring.application.name} @ ${server.port}
